// Package captured evidence as a portable, offline review canvas. No game assets are added.
// node scripts/review-canvas.mjs /tmp/touchline-review /path/to/claude/scratchpad/before
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
const [root, original] = process.argv.slice(2);
if (!root || !original) throw new Error('Pass the review capture directory and original pre-fix directory');
const esc = s => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const png = path => 'data:image/png;base64,' + readFileSync(path).toString('base64');
const source = readFileSync('src/ui/styles.ts', 'utf8');
const tokens = [...source.matchAll(/^  (--(?:tl|art)-[\w-]+):\s*([^;]+);/gm)].map(m => [m[1], m[2]]);
const pairs = [
  ['Numeric columns', '1280-09-table', original, 'Each numeric heading shares the right edge of its data column. Original capture uses a different career; compare alignment, not results.'],
  ['Fixtures', '390-10-fixtures', original, 'Border-box keeps the complete score inside the card. Passive rows no longer suggest a click. Original capture uses a different career.'],
  ['Phone tactics', '390-08-tactics', join(root,'before-layout'), 'The entire pitch fits. Grid children may shrink; the board retains its 68:92 ratio. Enlarged targets and two-row navigation stay reachable.'],
  ['Tablet navigation', '768-09-table', join(root,'before-layout'), 'All seven labels remain visible in the bottom navigation. Its stacking context now sits above page cards.'],
  ['Settings controls', '390-12-settings', join(root,'before-layout'), 'Small controls now have at least 56px targets, with choices wrapping when necessary.'],
  ['Club identity', '390-04-identity', join(root,'before-layout'), 'Badge options, palette controls and text fields have larger targets. Input text is 16px. Scroll to reach optional choices.'],
];
const boards = pairs.map(([title,name,before,note],i) => `<section id="board-${i}" class="board"><h2>${esc(title)}</h2><p>${esc(note)}</p><div class="pair"><figure><figcaption>Before · ${name.split('-')[0]}px</figcaption><img loading="lazy" src="${png(join(before,name+'.png'))}" alt="${esc(title)} before the review"></figure><figure><figcaption>Applied direction · ${name.split('-')[0]}px</figcaption><img loading="lazy" src="${png(join(root,'after',name+'.png'))}" alt="${esc(title)} after the review"></figure></div></section>`).join('');
const swatches = tokens.filter(([,v])=>/^(#|rgba?\()/.test(v)).map(([n,v])=>`<li><i style="background:${esc(v)}"></i><code>${esc(n)}</code><span>${esc(v)}</span></li>`).join('');
const values = tokens.filter(([,v])=>! /^(#|rgba?\()/.test(v)).map(([n,v])=>`<tr><th scope="row">${esc(n)}</th><td>${esc(v)}</td></tr>`).join('');
const gallery = ['390-01-menu','390-02-letter','390-03-pick','390-05-contract','390-06-home','390-07-squad','390-11-transfers','390-13-player','390-14-match'].map(n=>`<figure><figcaption>${esc(n.replace(/^390-\d+-/,''))} · 390px</figcaption><img loading="lazy" src="${png(join(root,'after',n+'.png'))}" alt="Reviewed ${esc(n)} screen"></figure>`).join('');
const html = `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Touchline design review</title><style>
:root{color-scheme:dark;--accent:#2fa85c}*{box-sizing:border-box}body{margin:0;background:#05130c;color:#f1f8f2;font:16px/1.55 system-ui,sans-serif}header,main{max-width:1440px;margin:auto;padding:32px 24px}h1{font-size:clamp(32px,5vw,64px);line-height:1.05;letter-spacing:-.035em;margin:12px 0 20px}h2{font-size:28px;letter-spacing:-.02em}p{max-width:74ch;color:#a9c7b3}a{color:#b4edca}nav{display:flex;gap:8px;flex-wrap:wrap}nav a,button{display:inline-flex;align-items:center;min-height:56px;padding:10px 16px;border:1px solid #426550;border-radius:8px;background:#10291c;color:#f1f8f2;font:inherit}a:focus-visible,button:focus-visible,input:focus-visible{outline:3px solid #62b9ff;outline-offset:3px}.board{padding:24px 0 48px;border-top:1px solid #294c37;scroll-margin-top:20px}.pair{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:24px}figure{margin:0;min-width:0}figcaption{padding:12px 0;color:#a9c7b3}img{display:block;width:100%;height:auto;border:1px solid #294c37;border-radius:13px}.pair img{max-height:900px;object-fit:contain;object-position:top;background:#0a2015}.swatches{list-style:none;padding:0;display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:16px}.swatches li{display:grid;grid-template-columns:48px 1fr;gap:4px 12px}.swatches i{grid-row:span 2;border:1px solid #547660;border-radius:8px}.swatches span{font-size:13px;color:#a9c7b3}table{border-collapse:collapse;width:100%}th,td{text-align:left;border-bottom:1px solid #294c37;padding:12px;overflow-wrap:anywhere}th{width:36%}.table-wrap{overflow-x:auto}.gallery{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:24px}.sample{border:1px solid var(--accent);border-radius:13px;padding:24px;background:#10291c}.sample strong{color:var(--accent);font-size:30px;font-variant-numeric:tabular-nums}.controls{display:flex;align-items:center;gap:16px;flex-wrap:wrap}input[type=color]{width:56px;height:56px;border:0;background:none}.note{padding:16px;border:1px solid #426550;border-radius:8px}.single .pair{grid-template-columns:1fr}.single .pair figure:first-child{display:none}@media(max-width:700px){header,main{padding:24px 16px}.pair,.gallery{grid-template-columns:1fr}th{width:45%}}@media print{nav,.controls{display:none}.board{break-before:page}body{print-color-adjust:exact}}
</style><header><p>Touchline · design review · 8 September 2026</p><h1>The whole pitch.<br>Every control within reach.</h1><p>Preserve the dusk control room, club colours, system typography and procedural illustrations. The applied direction repairs alignment, clipping, navigation visibility and input size inside the existing game.</p><p class="note">Offline HTML canvas, not a Claude Design document. Artboards are actual browser captures. Pale bands in some screenshots are the recorded SwiftShader rendering limitation, not a proposed surface treatment.</p><nav><a href="#board-0">Comparisons</a><a href="#tokens">Design tokens</a><a href="#gallery">Screen gallery</a><a href="audit.md">Written audit</a></nav></header><main><div class="controls"><button id="toggle" aria-pressed="false">Show applied direction only</button><button onclick="print()">Print / save PDF</button></div>${boards}<section class="board" id="tokens"><h2>The game's own system</h2><p>Values extracted directly from src/ui/styles.ts. Club colours are neutral defaults rebound per career. This sample changes independently of the captured screens.</p><div class="controls"><label for="accent">Try a club accent</label><input id="accent" type="color" value="#2fa85c"></div><div class="sample"><strong>4–2</strong><p>System stack · tabular scores · club identity</p></div><ul class="swatches">${swatches}</ul><div class="table-wrap"><table><caption>Non-colour tokens</caption><tbody>${values}</tbody></table></div><h3>Type and spacing in use</h3><p>Body 15px / 1.5; table data 14px; numeric headings 10px; formation title 30px / 800. Card padding 18px; row padding 12px × 16px; grid gap 14px; navigation targets 56px. Radius tokens: 8 / 13 / 20px. These are implementation values, not a new imported scale.</p></section><section id="gallery" class="board"><h2>The rest of the game</h2><p>Representative phone captures from the same deterministic career. The full four-width measurement set is preserved beside this audit.</p><div class="gallery">${gallery}</div></section></main><script>
document.getElementById('toggle').onclick=function(){const on=document.body.classList.toggle('single');this.setAttribute('aria-pressed',String(on));this.textContent=on?'Show before and after':'Show applied direction only'};document.getElementById('accent').oninput=function(){document.documentElement.style.setProperty('--accent',this.value)};
</script></html>`;
mkdirSync('docs/design-review', {recursive:true});
writeFileSync('docs/design-review/canvas.html',html);
console.log('review canvas: six comparison artboards, token board and nine-screen gallery');
